pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                script {
                    // Create a simple Java project structure
                    sh '''
                    mkdir -p src/main/java/com/example
                    echo "package com.example;

                    public class HelloWorld {
                        public static void main(String[] args) {
                            System.out.println(\\"Hello, World!\\");
                        }
                    }" > src/main/java/com/example/HelloWorld.java
                    
                    echo "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>
                    <project xmlns=\\"http://maven.apache.org/POM/4.0.0\\"
                             xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\"
                             xsi:schemaLocation=\\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/POM/4.0
